### ISSUE TITLE
Singularity Hub

### ISSUE THREAD

**Issue by vsoch** [NikkiBytes/NIBL#1]
hey @NikkiBytes ! I noticed you had a few containers on Singularity Hub, and that they didn't have any builds. I want to offer to help debug / look into if there are issues. For example, a few of the apt-get install -y statements don't have the `-y` to indicate yes. Let me know if you want some help!

**Comment by NikkiBytes** [comment]
hey @v yes actually I would love help....let me determine exactly what before I ask....let me let you know right now the cluster I am working on has Singularity 2.2.1 on it ..... they are working on upgrading to 2.4 because I want to start using the Singularity hub. 
But last week you guys helped to create the container than shell and use the command.....it works but when running my command in the shell it told me I needed packages installed....which the docker should have imported... that I don't understand... it looks like this: 

`$ singularity shell -B /projects/niblab/data:/projects/niblab/data -B /projects/niblab/test:/projects/niblab/test heudiconv.img
Singularity: Invoking an interactive shell within container...

Singularity.heudiconv.img> heudiconv -d /data/{subject}/SM*/raw/SM*/*/*.dcm -s SugarMama -f /heuristics/convertall.py -c none -o /out
Traceback (most recent call last):
  File "/usr/local/bin/heudiconv", line 29, in <module>
    import dcmstack as ds
ModuleNotFoundError: No module named 'dcmstack'
Singularity.heudiconv.img> `

**Comment by vsoch** [comment]
hey @NikkiBytes ! I will get a build going and see if I can help debug.

**Comment by vsoch** [comment]
I think there was likely a bug with permissions with the older image - I can't reproduce the error:

```
Singularity test.simg:/tmp/test> python
Python 2.7.13 |Anaconda, Inc.| (default, Sep 22 2017, 00:47:24) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dcmstack as ds
>>> 
```
no import error!

It also seems to work ok if I just pull it:

```
singularity pull docker://nipy/heudiconv
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
Docker image path: index.docker.io/nipy/heudiconv:latest
Cache folder set to /home/vanessa/.singularity/docker
[14/14] |===================================| 100.0% 
Importing: base Singularity environment
Importing: /home/vanessa/.singularity/docker/sha256:8ad8b3f87b378cfae583fef34e47a3c9203847d779961b7351cbf786af0bc09f.tar.gz
Importing: /home/vanessa/.singularity/docker/sha256:3ad2947cffd14188d264bdba1bcc286996499649510b895c3141ba2fb98e41bb.tar.gz
Importing: /home/vanessa/.singularity/docker/sha256:f8f7db357f2cd260e83f15775fbdcbe07b03b6ec85e5fd467d18787b8897f630.tar.gz
Importing: /home/vanessa/.singularity/docker/sha256:d4f79130294dbeb28148cebb31bfe376db3fc8ba1da9c251e3527eb78fd27f76.tar.gz
Importing: /home/vanessa/.singularity/docker/sha256:be3f0c098ec8b97b70b5783f752d2223953835ba92ae1de0aa277acc979833de.tar.gz
Importing: /home/vanessa/.singularity/docker/sha256:1362d1c7fda7d86e6572795b6a1052ae17770bea90d7ca0f8a9731056b97d11d.tar.gz
Importing: /home/vanessa/.singularity/docker/sha256:134947830e6c45c358ed3ba2cc2153f40ccd3286a76ee19300c4f401596aa66e.tar.gz
Importing: /home/vanessa/.singularity/docker/sha256:b4cd944ee15303aae23176a676046e776205a4b2d99de6af726441837a1e4810.tar.gz
Importing: /home/vanessa/.singularity/docker/sha256:d5ac33dbc373ea4eca1d4288593050177bed9228662cd6a1c579ff8cc78e2329.tar.gz
Importing: /home/vanessa/.singularity/docker/sha256:d5ac33dbc373ea4eca1d4288593050177bed9228662cd6a1c579ff8cc78e2329.tar.gz
Importing: /home/vanessa/.singularity/docker/sha256:f010cb91ee3086cdd4a5a13417119c174fba0d4bb05290dcb9e98779c639e41f.tar.gz
Importing: /home/vanessa/.singularity/docker/sha256:3d464fee79acdcb699b62413e90c542a1f83ad85e6c686174eeba62147cb8b80.tar.gz
Importing: /home/vanessa/.singularity/docker/sha256:48b955b6762fe2418c2f838619d24ad89c115f52d5ff6a7d5b2456ee4dad48a9.tar.gz
Importing: /home/vanessa/.singularity/docker/sha256:2cf84e3e53ae7bccec76a93fae8564e4e74555ba36b3b943e60a46fd0627414c.tar.gz
Importing: /home/vanessa/.singularity/metadata/sha256:c064c5a2c8a9f6a912609133e7ab920d9a7978202b176a7804a95c34b49ee74d.tar.gz
WARNING: Building container as an unprivileged user. If you run this container as root
WARNING: it may be missing some functionality.
Building Singularity image...
Singularity container built: ./heudiconv.img
Cleaning up...
vanessa@singularity-nginx:/tmp/test$ singularity shell heudiconv.img 
Singularity: Invoking an interactive shell within container...

Singularity heudiconv.img:/tmp/test> python
Python 2.7.13 |Anaconda, Inc.| (default, Sep 22 2017, 00:47:24) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dcmstack as ds

```
Have you tried building locally with Singularity 2.4? And maybe you could ask @satra to connect it to Singularity Hub to build the image with 2.4?

**Comment by NikkiBytes** [comment]
hey @v so I created another image, right now I am using the v2.2 because my admin still hasn't upgraded~ so I can't use the pull....but I did create another image and here it is still giving me the same issue...

locally on my host it looks:

`singularity shell heudiconv3.img
Singularity: Invoking an interactive shell within container...

Singularity.heudiconv3.img> python
Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dcmstack as ds
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named dcmstack
`

In the HPC I got the same error...
`
$ singularity shell heudiconv.img
Singularity: Invoking an interactive shell within container...

Singularity.heudiconv.img> python
Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dcmstack as ds
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'dcmstack'`



Initially I thought maybe it was the python version...but I get the same error with both. Could it possibly be an issue with the v2.2? I can install 2.4 locally and see what I get.

**Comment by vsoch** [comment]
hey @NikkiBytes , so I think the issue **is** with the version - we had some linking and permissions issues with earlier ones. Here are some ideas:

- First download and install 2.4 on your local computer. Build the image and confirm that it works.

To build, you can try both of squash fs and ext3 (old format)

```
sudo singularity build heuro-squash.simg Singularity  #squashfs
sudo singularity build --writable heuro.simg Singularity  #ext3
```
Then for both of the above, after confirming it works locally, test to see if it works on your cluster.

- If yes, yay! We're done
- If no, then what about we try to export the contents of the newer image to an older Singularity? You would need both versions installed to do this. And you could try both using singularity 2.2 import from the 2.4 image (or an extracted tar of the 2.4) OR you could try singularity export with 2.4 >> 2.2.

**Comment by vsoch** [comment]
oh also, you don't need singularity pull to move containers, you can build locally and then transfer with sftp, scp, etc.

**Comment by NikkiBytes** [comment]
@v okay perfect, I am copying my images to the cluster with scp, it just takes a bit of time....one of the main reasons I asked them to upgrade! 
But v2.4 does not produce the error:

`singularity shell heudiconv3.img
Singularity: Invoking an interactive shell within container...

Singularity heudiconv3.img:~> python
Python 2.7.13 |Anaconda, Inc.| (default, Sep 22 2017, 00:47:24) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dcmstack as ds
`

Unfortunately I will have to wait to test it on the HPC until they upgrade it. Thank you so much, I would have kept trying to figure out that error and wasted a lot of time, thank you!

**Comment by vsoch** [comment]
woohoo! Yeah, sometimes that's the way of the world - finding weird and arduous hacks to get what you want working! Keep the issue open if you want to ping me at some point for more help, otherwise go ahead and close! Actually I think I'd be notified either way if you close --> open vs just leave open :)
